<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HP330.Protocol/HP330.Protocol.csproj" />
    <ProjectReference Include="../HP330.Serial/HP330.Serial.csproj" />
  </ItemGroup>
</Project>
